
package GUI;

import Clases.OpcionesMenu;

/**
 *
 * @author Joss
 */
public class AgregarAlbum extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAlbum
     */
    public AgregarAlbum() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarAlbum = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblDisquera = new javax.swing.JLabel();
        lblArtistas = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtDisquera = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAniadir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTañadirAlbum = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIAgregarCancion = new javax.swing.JMenuItem();
        jMIBuscarAlbum = new javax.swing.JMenuItem();
        jMIDetalleAlbum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(128, 205, 228));
        setSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(29, 79, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgregarAlbum.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblAgregarAlbum.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarAlbum.setText("Añadir Album ");
        jPanel1.add(lblAgregarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre1.setText("Nombre :");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblAnio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(51, 51, 51));
        lblAnio.setText("Año lanzamiento  :");
        jPanel1.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblDisquera.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblDisquera.setForeground(new java.awt.Color(51, 51, 51));
        lblDisquera.setText("Disquera  :");
        jPanel1.add(lblDisquera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lblArtistas.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblArtistas.setForeground(new java.awt.Color(51, 51, 51));
        lblArtistas.setText("Artistas  :");
        jPanel1.add(lblArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtNombre.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, 20));

        txtAnio.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        txtDisquera.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        txtDisquera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisqueraActionPerformed(evt);
            }
        });
        jPanel1.add(txtDisquera, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));

        txtArtista.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        txtArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistaActionPerformed(evt);
            }
        });
        jPanel1.add(txtArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));

        btnAgregar.setBackground(new java.awt.Color(189, 205, 228));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(51, 51, 51));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 255), null, null));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 80, 30));

        btnAniadir.setBackground(new java.awt.Color(189, 205, 228));
        btnAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/simboloSuma.png"))); // NOI18N
        btnAniadir.setBorder(null);
        jPanel1.add(btnAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jTañadirAlbum.setBackground(new java.awt.Color(189, 205, 228));
        jTañadirAlbum.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jTañadirAlbum.setForeground(new java.awt.Color(51, 51, 51));
        jTañadirAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Año Lanzamiento", "Disquera", "Artista"
            }
        ));
        jTañadirAlbum.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTañadirAlbum.setSelectionForeground(new java.awt.Color(204, 0, 204));
        jScrollPane2.setViewportView(jTañadirAlbum);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 250, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/descarga (13).jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 340));

        jMenuBar1.setBackground(new java.awt.Color(189, 205, 228));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        jMenu1.setForeground(new java.awt.Color(102, 102, 102));
        jMenu1.setText("Salir");

        jMISalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMISalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(102, 102, 102));
        jMenu2.setText("Opciones");

        jMIAgregarCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIAgregarCancion.setForeground(new java.awt.Color(102, 102, 102));
        jMIAgregarCancion.setText("Agregar-Canción");
        jMIAgregarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarCancionActionPerformed(evt);
            }
        });
        jMenu2.add(jMIAgregarCancion);

        jMIBuscarAlbum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIBuscarAlbum.setForeground(new java.awt.Color(102, 102, 102));
        jMIBuscarAlbum.setText("Buscar-Album");
        jMIBuscarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuscarAlbumActionPerformed(evt);
            }
        });
        jMenu2.add(jMIBuscarAlbum);

        jMIDetalleAlbum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIDetalleAlbum.setForeground(new java.awt.Color(102, 102, 102));
        jMIDetalleAlbum.setText("Detalle-Album");
        jMIDetalleAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDetalleAlbumActionPerformed(evt);
            }
        });
        jMenu2.add(jMIDetalleAlbum);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtDisqueraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisqueraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisqueraActionPerformed

    private void txtArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jMIAgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarCancionActionPerformed
         OpcionesMenu.agregarCancion(this);
    }//GEN-LAST:event_jMIAgregarCancionActionPerformed

    private void jMIBuscarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarAlbumActionPerformed
     OpcionesMenu.buscarAlbum(this);
    }//GEN-LAST:event_jMIBuscarAlbumActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        OpcionesMenu.salir(this);
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMIDetalleAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDetalleAlbumActionPerformed
     OpcionesMenu.detalleAlbum(this);
    }//GEN-LAST:event_jMIDetalleAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAniadir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMIAgregarCancion;
    private javax.swing.JMenuItem jMIBuscarAlbum;
    private javax.swing.JMenuItem jMIDetalleAlbum;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTañadirAlbum;
    private javax.swing.JLabel lblAgregarAlbum;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblArtistas;
    private javax.swing.JLabel lblDisquera;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtDisquera;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
