/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import javax.swing.ImageIcon;

public class Homepage extends javax.swing.JFrame {

    public Homepage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgreCancion = new javax.swing.JButton();
        btnAgreAlbum = new javax.swing.JButton();
        btnBuscarAlbum = new javax.swing.JButton();
        btnDetalleAlbum = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cine");
        setBackground(new java.awt.Color(230, 242, 242));

        btnAgreCancion.setBackground(new java.awt.Color(42, 39, 39));
        btnAgreCancion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAgreCancion.setForeground(new java.awt.Color(255, 255, 255));
        btnAgreCancion.setText("Agregrar Canción");
        btnAgreCancion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgreCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreCancionActionPerformed(evt);
            }
        });

        btnAgreAlbum.setBackground(new java.awt.Color(42, 39, 39));
        btnAgreAlbum.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAgreAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnAgreAlbum.setText("Agregrar Album");
        btnAgreAlbum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgreAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreAlbumActionPerformed(evt);
            }
        });

        btnBuscarAlbum.setBackground(new java.awt.Color(42, 39, 39));
        btnBuscarAlbum.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBuscarAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlbum.setText("Buscar Album");
        btnBuscarAlbum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlbumActionPerformed(evt);
            }
        });

        btnDetalleAlbum.setBackground(new java.awt.Color(42, 39, 39));
        btnDetalleAlbum.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDetalleAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalleAlbum.setText("Ver Lista de Canciones");
        btnDetalleAlbum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDetalleAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleAlbumActionPerformed(evt);
            }
        });

        jLFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/descarga (13).jpeg"))); // NOI18N
        jLFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetalleAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalleAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(jLFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgreAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreAlbumActionPerformed
        AgregarAlbum jfalbum = new AgregarAlbum();
        jfalbum.setVisible(true);
    }//GEN-LAST:event_btnAgreAlbumActionPerformed

    private void btnAgreCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreCancionActionPerformed
        AgregarCancion jfcancion = new AgregarCancion ();
        jfcancion.setVisible(true);
    }//GEN-LAST:event_btnAgreCancionActionPerformed

    private void btnBuscarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlbumActionPerformed
        BuscarAlbum jfbuscarAlbum = new BuscarAlbum ();
        jfbuscarAlbum.setVisible(true);
    }//GEN-LAST:event_btnBuscarAlbumActionPerformed

    private void btnDetalleAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleAlbumActionPerformed
        DetalleAlbum jfdetalleAlbum = new DetalleAlbum ();
        jfdetalleAlbum.setVisible(true);
    }//GEN-LAST:event_btnDetalleAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgreAlbum;
    private javax.swing.JButton btnAgreCancion;
    private javax.swing.JButton btnBuscarAlbum;
    private javax.swing.JButton btnDetalleAlbum;
    private javax.swing.JLabel jLFondo;
    // End of variables declaration//GEN-END:variables
}
